version: '3.8'

services: 
  postgres:
    image: postgis/postgis:15-3.3
    container_name: huma-postgres
    environment:
      POSTGRES_USER: huma
      POSTGRES_PASSWROD: huma_pass
      POSTGRES_DB: humadb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  resis:
    image: redis:7
    container_name: huma_redis
    ports:
      - '6379:6379'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: huma-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

  minio:
    image: minio/minio
    container_name: huma-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always

volumes:
 pgdata: